### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by ashipaek0** [umpirsky/rhytmbox-tunein-import#2]
Traceback (most recent call last):
  File "rhytmbox-tunein-import/import.py", line 34, in <module>
    location.text = urllib2.urlopen(child.get('URL')).read().splitlines()[0]
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 420, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'

**Comment by umpirsky** [comment]
Unfortunately, I have no time to fix the issue. 

Looks like issue in urllib2. :o
